name: gather-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcalm=2.2.3
  - biopython=1.83
  - colorama=0.4.6
  - joblib=1.4.2
  - networkx=3.1
  - numpy=1.22.3
  - pandas=1.4.2
  - python=3.8
  - python-dateutil=2.9.0
  - pytz=2024.2
  - six=1.16.0
  - tqdm=4.67.0
  - pip
  - pip:
    - git+https://github.com/Neuroimmunology-UiO/gather.git
