package:
  name: gather
  version: "0.1.0"

source:
  path: ../

build:
  noarch: python
  script: python -m pip install .

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.19
    - pandas
    - networkx
    - joblib
    - tqdm
    - biopython
    - argcomplete
    - glob2
    - rich
    - bioconda::bcalm =2.2.3  

about:
  home: https://github.com/Neuroimmunology-UiO/gather
  license: Apache-2.0
  summary: "Assembly of heavy and light chain BCRs using De Bruijn graphs."
  description: |
    Gather is a Python-based toolkit for assembling heavy and light chain BCRs from sequence data using 
    De Bruijn graphs. It includes modules for processing 10X and single-cell data.

extra:
  recipe-maintainers:
    - your_anaconda_username

