package:
  name: gather
  version: 0.1.0

source:
  path: ../  # Absolute path to your package directory

build:
  noarch: python
  script: python -m pip install .

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy >=1.19
    - pandas
    - networkx
    - joblib
    - tqdm
    - biopython
    - bioconda::bcalm

about:
  home: https://github.com/Neuroimmunology-UiO/GATHER.git
  license: Apache 2.0
  summary: "Assembly of heavy and light chain BCR using the De Bruijn graph."

extra:
  recipe-maintainers:
    - your_anaconda_username
